/**
 * Which small icon a provider shows beside its name.
 *
 * These are arbitrary self-hosted OpenAI-compatible endpoints, not a fixed catalogue of
 * vendors — `kind` is a person's own label, not something detected from `base_url`. A kind with
 * a real logo file under `static/providers/` draws that; a kind without one (nothing sourced
 * yet, or `generic`) falls back to a monogram instead of a broken image. `'custom'` is the one
 * kind with a real *uploaded* image — see {@link api.logoUrl} — and only it needs the
 * upload/serve machinery on the API.
 *
 * The files themselves are not fetched or generated by this codebase: trademark usage is a
 * per-vendor judgement call, made by whoever deploys this, not something to automate. SVG is the
 * target format for all of them — drop one at `static/providers/<name>.svg` and add it to
 * `LOGO_FILES` below. Most of these came from Simple Icons (simpleicons.org); OpenAI isn't in
 * that set and was sourced separately. Only `llamacpp` (and the two kinds that never get a
 * bundled file, `generic`/`custom`) still draws the monogram.
 */

import { api, type Provider, type ProviderKind } from '$lib/api/client';

export const PROVIDER_KINDS: ProviderKind[] = [
	'openai',
	'anthropic',
	'google',
	'mistral',
	'openrouter',
	'lmstudio',
	'ollama',
	'vllm',
	'llamacpp',
	'generic',
	'custom'
];

// One bundled SVG per kind that has one. `generic` and `custom` are deliberately absent:
// `custom` is a person's own upload, and `generic` names no vendor to have a mark for.
// `llamacpp` is absent too, not deliberately — nothing has been sourced for it yet, so it draws
// the monogram like `generic`/`custom` do.
const LOGO_FILES: Partial<Record<ProviderKind, string>> = {
	openai: '/providers/openai.svg',
	anthropic: '/providers/claude.svg',
	google: '/providers/google.svg',
	mistral: '/providers/mistral.svg',
	openrouter: '/providers/openrouter.svg',
	lmstudio: '/providers/lmstudio.svg',
	ollama: '/providers/ollama.svg',
	vllm: '/providers/vllm.svg'
};

function monogram(letters: string, background: string): string {
	const svg =
		`<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">` +
		`<rect width="28" height="28" rx="7" fill="${background}"/>` +
		`<text x="14" y="19" font-family="system-ui, sans-serif" font-size="11" ` +
		`font-weight="600" fill="#fff" text-anchor="middle">${letters}</text></svg>`;
	return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

// The placeholder for every kind, drawn rather than sourced — used as the fallback when a kind
// has no file in `LOGO_FILES` yet, and as the `<img onerror>` target if a listed file is missing
// or fails to load (a data URI, so it can never itself fail to draw).
const FALLBACK_ICONS: Record<ProviderKind, string> = {
	openai: monogram('OA', '#10a37f'),
	anthropic: monogram('AN', '#d97757'),
	google: monogram('G', '#4285f4'),
	mistral: monogram('MI', '#fa520f'),
	openrouter: monogram('OR', '#6467f2'),
	lmstudio: monogram('LM', '#4c5cf0'),
	ollama: monogram('OL', '#1a1a1a'),
	vllm: monogram('VL', '#2f6f4f'),
	llamacpp: monogram('LC', '#8a5a2c'),
	generic: monogram('••', '#71717a'),
	custom: monogram('?', '#71717a')
};

/** The image to draw for one provider — its uploaded logo if it has one, otherwise the
 * bundled file or monogram for its kind. */
export function providerIcon(provider: Provider): string {
	if (provider.kind === 'custom' && provider.logo_media_type) return api.logoUrl(provider.name);
	return kindIcon(provider.kind);
}

/** The fallback for one provider's icon, if {@link providerIcon} fails to load — passed to
 * `<img onerror>` rather than assumed, since a bundled file might be missing on disk even
 * though it is listed here. */
export function providerFallbackIcon(provider: Provider): string {
	return kindFallbackIcon(provider.kind);
}

/** The icon for a kind on its own, regardless of any upload — used by the kind picker itself,
 * where every option needs to show what it *would* look like. */
export function kindIcon(kind: ProviderKind): string {
	return LOGO_FILES[kind] ?? kindFallbackIcon(kind);
}

/** The monogram for a kind, bypassing any bundled file — the `<img onerror>` target for
 * {@link kindIcon}. */
export function kindFallbackIcon(kind: ProviderKind): string {
	return FALLBACK_ICONS[kind] ?? FALLBACK_ICONS.generic;
}
